# Generated by Django 5.1.2 on 2024-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
